<a href="https://colab.research.google.com/github/idrisello/my-numpy-lessons/blob/main/np_3_lesson_savefile.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr=np.arange(12)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
np.save('data',arr) #save orqali npga fila qoshamz va malumot saqlaymiz
arr1=np.load("data.npy") #load orqali saqlagan filemizni qayta yuklam npga qoshamza p/s toliq file nomi .keyingi sozlari bn yozilishi kere
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
arr2=np.arange(30).reshape(6,5)
arr2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [ ]:
np.savez('arrays',a=arr1, b=arr2) #savez orqali 2xil malumotlarni kalit bn saqlab keyinchalik kaliti bn murojaat qla olamz

In [ ]:
arrays=np.load("arrays.npz")

In [ ]:
arrays['a']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
arr3=np.random.randn(7)
arr3

array([-1.7601327 , -0.81880629,  0.03285161,  0.65945548,  0.28614507,
        2.26858139, -0.91544729])

In [ ]:
np.savez_compressed('arrays-compressed', a=arr1, b=arr2, c=arr3) #2va undan ortiq arraylarni hajmini qisqartirib berib saqlaydi

In [ ]:
new_data=np.load('arrays-compressed.npz')
new_data['c']

array([-1.7601327 , -0.81880629,  0.03285161,  0.65945548,  0.28614507,
        2.26858139, -0.91544729])