<a href="https://colab.research.google.com/github/idrisello/my-numpy-lessons/blob/main/np_6_lessons_extrainfo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view() #view can change original arr
arr[0] = 42
print(arr)


[42  2  3  4  5]


In [ ]:
arr00 = np.array([1, 2, 3, 4, 5])
x = arr00.copy()
y = arr00.view()
print(x.base) #base that returns None if the array owns the data.
print(y.base) #Otherwise, the base  attribute refers to the original object

None
[1 2 3 4 5]


In [5]:
arr1 = np.array([1, 2, 3, 4], ndmin=5) #Create an array with 5 dimensions using ndmin using a vector with values 1,2,3,4 and verify that last dimension has value 4
print(arr1)


[[[[[1 2 3 4]]]]]


In [7]:
rr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = rr.reshape(2, 2, -1)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


# **Iterating**

In [8]:
arr01 = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr01:
  for y in x:
    print(y)

1
2
3
4
5
6


In [11]:
arr02 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for xx in arr02:
  print(xx)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [13]:
array1 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(array1): #  function that provides an efficient way to iterate over elements in one or more arrays.
  print(x)

1
2
3
4
5
6
7
8


In [18]:
arr03 = np.array([1, 2, 3])

for idx, xl in np.ndenumerate(arr03): # is a function that provides an iterator yielding index and value tuples for elements in one or more arrays. It is similar to enumerate()
  print(idx, xl)

(0,) 1
(1,) 2
(2,) 3


# **Joining**
# joining means putting contents of two or more arrays in a single array.

In [20]:
arr33 = np.array([1, 2, 3])

arr23 = np.array([4, 5, 6])

arr_conc = np.concatenate((arr33, arr23)) #join 2array into single arr

print(arr_conc)

[1 2 3 4 5 6]


In [23]:
arr11 = np.array([[1, 2], [3, 4]])

arr12 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr11, arr12), axis=0)

print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [27]:
arr4 = np.array([1, 2, 3])

arr5 = np.array([4, 5, 6])

arr_stack = np.stack((arr4, arr5), axis=0) #Stacking is same as concatenation, the only difference is that stacking is done along a new axis.

print(arr_stack)

[[1 2 3]
 [4 5 6]]


In [30]:
arr6 = np.array([1, 2, 3])

arr7 = np.array([4, 5, 6])

arr_hstack = np.hstack((arr6, arr7)) # hstack() to stack along rows.

print(arr_hstack)

[1 2 3 4 5 6]


In [33]:
arr_vstack=np.vstack((arr6,arr7)) #vstack()  to stack along columns.
arr_vstack

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
arr_dstack=np.dstack((arr6,arr7)) #dstack() to stack along height, which is the same as depth.
arr_dstack

array([[[1, 4],
        [2, 5],
        [3, 6]]])

# **Spliting**
# splitting is reverse operation of Joining.

#Joining merges multiple arrays into one and Splitting breaks one array into multiple.

In [35]:
arr9 = np.array([1, 2, 3, 4, 5, 6])

newarr9 = np.array_split(arr9, 3)#divide into 3parts
newarr9

[array([1, 2]), array([3, 4]), array([5, 6])]

In [37]:
arr10 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr10 = np.array_split(arr10, 3)

print(newarr10)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [38]:
arr13 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr13 = np.array_split(arr13, 3, axis=1) #split the 2-D array into three 2-D arrays along rows.

print(newarr13)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


**Note: Similar alternates to vstack() and dstack() are available as vsplit() and dsplit().**

# **Search**
# You can search an array for a certain value, and return the indexes that get a match.

# To search an array, use the where() method.

In [40]:
arr14 = np.array([1, 2, 3, 4, 5, 4, 4])

arr_where = np.where(arr14 == 4)

print(arr_where)

(array([3, 5, 6]),)


In [42]:
arr15 = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x15 = np.where(arr15%2 == 0)

print(x15)

(array([1, 3, 5, 7]),)


In [47]:
arr_16 = np.array([6, 7, 8, 9])
arr_search = np.searchsorted(arr_16, 7) #find the indexes where the value 7 should be inserted:

print(arr_search)

1


In [50]:
x_16 = np.searchsorted(arr_16, 7, side='right') #Find the indexes where the value 7 should be inserted, starting from the right:

print(x_16)

2


In [51]:
arr17 = np.array([1, 3, 5, 7])

x17= np.searchsorted(arr17, [2, 4, 6]) #Find the indexes where the values 2, 4, and 6 should be inserted:

print(x17)


[1 2 3]
