<a href="https://colab.research.google.com/github/idrisello/my-numpy-lessons/blob/main/np_8_lesson_uf.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

# ufuncs are used to implement vectorization in NumPy which is way faster than iterating over elements.

## They also provide broadcasting and additional methods like reduce, accumulate etc. that are very helpful for computation.

ufuncs also take additional arguments, like:

where boolean array or condition defining where the operations should take place.

dtype defining the return type of elements.

out output array where the return value should be copied.



In [5]:
# Define the function that calculates the values
def calculate_value(x, y):
    return x**2 + y**2

# Create a 3x3 array using the function and shape
result = np.fromfunction(calculate_value, (3, 3)) #alculate_value function takes the indices x and y and returns their squared sum.








print(result)


[[0. 1. 4.]
 [1. 2. 5.]
 [4. 5. 8.]]


In [10]:
def myadd(x, y):
  return x+y

myadd = np.frompyfunc(myadd, 2, 1)# method is used to construct an array by executing a specified function over each coordinate. It creates an array based on the output of a user-defined function that is applied to each element's indices.

print(myadd([1, 2, 3, 4], [5, 6, 7, 8]))

[6 8 10 12]


In [11]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.remainder(arr1, arr2) #functions return the remainder of the values in the first array corresponding to the values in the second array, and return the results in a new array.
#remainder=mod
print(newarr)

[ 1  6  3  0  0 27]


In [12]:
arr3=np.array([10,20,30,40,50,60])
arr4=np.array([3,7,9,6,70,19])
arr_divmod=np.divmod(arr3,arr4) #function return both the quotient and the the mod. The return value is two arrays, the first array contains the quotient and second array contains the mod.

(array([3, 2, 3, 6, 0, 3]), array([ 1,  6,  3,  4, 50,  3]))

In [16]:
arr = np.array([-1, -2, 1, 2, 3, -4])
newarr2 = np.abs(arr) #returns the magnitude (also known as the modulus) of the complex number.

print(newarr2)

[1 2 1 2 3 4]


# **Truncation**
Remove the decimals, and return the float number closest to zero. Use the trunc() and fix() functions.*

In [17]:
arr5 = np.trunc([-3.1666, 3.6667])
arr5

array([-3.,  3.])

In [18]:
arr6=np.fix([4.9876,2.77601])
arr6

array([4., 2.])

In [21]:
arr7=np.around([3.43,5,7.78]) #The around() function increments preceding digit or decimal by 1 if >=5 else do nothing.
#E.g. round off to 1 decimal point, 3.16666 is 3.2
arr7

array([3., 5., 8.])

In [24]:
#The floor() function rounds off decimal to nearest lower integer.
arr8 = np.floor([-3.1666, 3.6667])
print(arr8)

[-4.  3.]


In [26]:
#The ceil() function rounds off decimal to nearest upper integer.
arr9=np.ceil([-4,34,-5,7.99899,3.1])
arr9

array([-4., 34., -5.,  8.,  4.])

In [32]:
arr1


array([10, 20, 30, 40, 50, 60])

In [33]:
arr2

array([ 3,  7,  9,  8,  2, 33])

In [28]:
arr_sum = np.sum([arr1, arr2]) #addition is done between two arguments whereas summation happens over n elements.
arr_add=np.add(arr1,arr2)
arr_sum

272

In [29]:
arr_add

array([13, 27, 39, 48, 52, 93])

In [34]:
newarr0 = np.sum([arr1, arr2], axis=1)#sum the numbers in each array.
newarr0

array([210,  62])

In [36]:
arr1

array([10, 20, 30, 40, 50, 60])

In [38]:
arr1.prod() #prod means multiply all elements in array each others

720000000

In [40]:
v=np.prod([arr1,arr2],axis=0)
v

array([  30,  140,  270,  320,  100, 1980])

In [42]:
#ummulative product means taking the product partially.

#E.g. The partial product of [1, 2, 3, 4] is [1, 1*2, 1*2*3, 1*2*3*4] = [1, 2, 6, 24]
#Perfom partial sum with the cumprod() function.
arr11 = np.array([5, 6, 7, 8])
newarr11 = np.cumprod(arr11)

print(newarr11)

[   5   30  210 1680]


In [44]:
#A discrete difference means subtracting two successive elements.

#E.g. for [1, 2, 3, 4], the discrete difference would be [2-1, 3-2, 4-3] = [1, 1, 1]

#To find the discrete difference, use the diff() function.
arr12 = np.array([10, 15, 25, 5])

newarr12 = np.diff(arr12)

print(newarr12)#Returns: [5 10 -20] because 15-10=5, 25-15=10, and 5-25=-20

[  5  10 -20]


In [45]:
#The Lowest Common Multiple is the smallest number that is a common multiple of two numbers.
num1 = 4
num2 = 6

x = np.lcm(num1, num2)

print(x)

12


In [46]:
arr13 = np.array([3, 6, 9])
#To find the Lowest Common Multiple of all values in an array, you can use the reduce() method.
xl = np.lcm.reduce(arr)#The reduce() method will use the ufunc, in this case the lcm() function, on each element, and reduce the array by one dimension.

print(xl)

18


In [48]:
#The GCD (Greatest Common Denominator), also known as HCF (Highest Common Factor) is the biggest number that is a common factor of both of the numbers.
num3= 6
num4 = 9

xx = np.gcd(num3, num4)
#Returns: 3 because that is the highest number both numbers can be divided by (6/3=2 and 9/3=3).
print(xx)

3


In [50]:
arr14 = np.array([20, 8, 32, 36, 16])

p = np.gcd.reduce(arr14)

print(p)

4


In [53]:
arr15 = np.array([1, 1, 1, 2, 3, 4, 5, 5, 6, 7])

x15 = np.unique(arr15)#method to find unique elements from any array.

print(x15)

[1 2 3 4 5 6 7]


In [57]:
arr16=np.array([1,2,3,4,3,7,8,6,4])

In [58]:
arr17=np.array([2,2,3,88,66,33,4])

In [60]:
newarr17=np.union1d(arr16,arr17)#To find the unique values of two arrays, use the union1d() method.
newarr17

array([ 1,  2,  3,  4,  6,  7,  8, 33, 66, 88])

In [61]:
newarr017=np.intersect1d(arr16,arr17)#To find only the values that are present in both arrays, use the intersect1d() method.
newarr017

array([2, 3, 4])

In [62]:
set1 = np.array([1, 2, 3, 4])
set2 = np.array([3, 4, 5, 6])

newarrset = np.setdiff1d(set1, set2, assume_unique=True)
#the setdiff1d() method takes an optional argument assume_unique, which if set to True can speed up computation. It should always be set to True when dealing with sets.
print(newarrset)


[1 2]
